ALTER TABLE Users
DROP CONSTRAINT PK_Users

ALTER TABLE Users
ADD CONSTRAINT PK_Person PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT UC_Users UNIQUE(Username)

ALTER TABLE Users
ADD CONSTRAINT CHK_Users CHECK(LEN(Password) >= 3)
